# Generated by Django 2.2.27 on 2022-02-26 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boutique',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='magazine',
            name='stock',
        ),
    ]
