# Generated by Django 3.2.2 on 2022-02-26 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Magazine',
        ),
    ]
