# Generated by Django 3.2.2 on 2022-02-26 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0002_delete_magazine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.CharField(max_length=32)),
                ('wilaya', models.CharField(max_length=40)),
                ('magaziniere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
            ],
        ),
    ]
