# Generated by Django 3.2.2 on 2021-08-27 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20210827_1520'),
        ('stock', '0003_auto_20210827_2221'),
    ]

    operations = [
    ]
