# Generated by Django 2.2.27 on 2022-02-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20220227_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boutique',
            name='magazinier',
            field=models.IntegerField(null=True),
        ),
    ]
