# Generated by Django 3.2.2 on 2021-08-27 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_merge_0002_auto_20210827_1520_0003_auto_20210827_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date_entree',
        ),
        migrations.RemoveField(
            model_name='article',
            name='prix_achat',
        ),
        migrations.RemoveField(
            model_name='article',
            name='qtStock',
        ),
    ]
