# Generated by Django 3.2.2 on 2022-02-26 13:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0005_auto_20220226_1332'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produit',
            new_name='Article',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='produit',
        ),
        migrations.AddField(
            model_name='stock',
            name='Article',
            field=models.ManyToManyField(blank=True, related_name='article', to='stock.Article'),
        ),
    ]
