# Generated by Django 3.2.2 on 2021-08-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20210827_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_entree',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='prix_achat',
            field=models.IntegerField(null=True),
        ),
    ]
