# Generated by Django 2.2.27 on 2022-02-27 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20220227_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boutique',
            name='magazinier',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
