# Generated by Django 2.2.27 on 2022-02-27 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20220227_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boutique',
            name='magazinier',
            field=models.IntegerField(null=True),
        ),
    ]
