# Generated by Django 3.2.2 on 2021-08-28 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0007_categorie_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='user',
        ),
        migrations.AddField(
            model_name='stock',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
