# Generated by Django 2.2.27 on 2022-02-27 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20220227_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boutique',
            name='magazinier',
        ),
    ]
