# Generated by Django 3.2.2 on 2021-08-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20210828_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='statut',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
