# Generated by Django 3.2.3 on 2021-08-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_auto_20210828_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='statut',
            field=models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], default='0', max_length=2, null=True),
        ),
    ]
