# Generated by Django 3.2.2 on 2021-08-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_alter_article_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='article',
            field=models.ManyToManyField(blank=True, to='stock.Article'),
        ),
    ]
