# Generated by Django 3.2.2 on 2021-08-29 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_alter_stock_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortir',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.categorie'),
        ),
        migrations.AlterField(
            model_name='sortir',
            name='date_sortie',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='sortir',
            name='qte',
            field=models.PositiveIntegerField(),
        ),
    ]
