# Generated by Django 3.2.6 on 2021-08-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_alter_stock_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='prix_achat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sortir',
            name='date_sortie',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='sortir',
            name='prix_sortie',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='sortir',
            name='qte',
            field=models.PositiveIntegerField(),
        ),
    ]
