# Generated by Django 3.2.6 on 2021-08-30 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_auto_20210830_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sortir',
            name='stock',
        ),
    ]
