# Generated by Django 3.2.6 on 2021-08-30 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_remove_sortir_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortir',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.stock'),
        ),
        migrations.AlterField(
            model_name='article',
            name='prix_achat',
            field=models.IntegerField(null=True),
        ),
    ]
