# Generated by Django 3.2.6 on 2021-08-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_auto_20210830_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortir',
            name='date_sortie',
            field=models.DateField(blank=True),
        ),
    ]
