# Generated by Django 3.2.6 on 2021-08-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_alter_sortir_date_sortie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortir',
            name='date_sortie',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
