# Generated by Django 3.2.6 on 2021-08-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0020_alter_sortir_date_sortie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='article',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='qte',
        ),
        migrations.AddField(
            model_name='facture',
            name='sorties',
            field=models.ManyToManyField(to='stock.Sortir'),
        ),
        migrations.AddField(
            model_name='facture',
            name='totalprix',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sortir',
            name='prix_sortie',
            field=models.FloatField(),
        ),
    ]
