# Generated by Django 3.2.2 on 2021-08-30 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_auto_20210829_2029'),
        ('stock', '0021_auto_20210830_1823'),
    ]

    operations = [
    ]
