# Generated by Django 3.2.2 on 2021-08-30 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0022_merge_0015_auto_20210829_2029_0021_auto_20210830_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sortir',
            name='categorie',
        ),
        migrations.AddField(
            model_name='facture',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.article'),
        ),
        # migrations.AddField(
        #     model_name='facture',
        #     name='qte',
        #     field=models.IntegerField(null=True),
        # ),
        # migrations.AlterField(
        #     model_name='sortir',
        #     name='date_sortie',
        #     field=models.DateField(blank=True, null=True),
        # ),
        migrations.AlterField(
            model_name='sortir',
            name='prix_sortie',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sortir',
            name='qte',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
