# Generated by Django 3.2.2 on 2021-08-31 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0024_auto_20210830_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortir',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.categorie'),
        ),
    ]
