# Generated by Django 3.2.6 on 2021-09-06 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0025_sortir_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facture',
            name='sorties',
            field=models.ManyToManyField(related_name='sorties', to='stock.Sortir'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='article',
            field=models.ManyToManyField(blank=True, related_name='article', to='stock.Article'),
        ),
    ]
