# Generated by Django 3.2.2 on 2021-09-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0026_auto_20210906_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='baarcode',
            field=models.ImageField(default='barcode.png', upload_to='article/codes'),
        ),
    ]
