# Generated by Django 3.2.2 on 2021-09-09 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0027_article_baarcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='baarcode',
            new_name='barcode',
        ),
    ]
