# Generated by Django 3.2.2 on 2021-09-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0028_rename_baarcode_article_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='barcode',
            field=models.ImageField(blank=True, upload_to='article/codes'),
        ),
    ]
