# Generated by Django 3.2.2 on 2021-09-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0029_alter_article_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='numero',
            field=models.IntegerField(blank=True),
        ),
    ]
