# Generated by Django 3.2.7 on 2021-09-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_manager'),
        ('stock', '0034_article_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='profile',
        ),
        migrations.AddField(
            model_name='article',
            name='profiles',
            field=models.ManyToManyField(null=True, related_name='profiles', to='accounts.Profile'),
        ),
    ]
