# Generated by Django 3.2.7 on 2021-09-14 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0034_alter_facture_sorties'),
        ('stock', '0036_remove_article_profiles'),
    ]

    operations = [
    ]
