# Generated by Django 3.2.2 on 2021-09-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0037_merge_20210914_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='quantité_en_vrac',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
