# Generated by Django 3.2.2 on 2021-09-21 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0039_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
