# Generated by Django 2.2.27 on 2022-02-24 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0041_auto_20220214_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='qte',
            field=models.IntegerField(null=True),
        ),
    ]
