# Generated by Django 3.2.2 on 2022-02-25 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0044_auto_20220224_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True)),
                ('nom', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(null=True)),
                ('date_entree', models.DateField(null=True)),
                ('prix_achat', models.IntegerField(null=True)),
                ('statut', models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], default='0', max_length=2, null=True)),
                ('quantité_en_vrac', models.PositiveIntegerField(null=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.categorie')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='article',
            name='user',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='article',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='commande',
        ),
        migrations.DeleteModel(
            name='Commande',
        ),
        migrations.DeleteModel(
            name='Panier',
        ),
        migrations.AlterField(
            model_name='entrer',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.produit'),
        ),
        migrations.AlterField(
            model_name='sortir',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.produit'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='article',
            field=models.ManyToManyField(blank=True, related_name='article', to='stock.Produit'),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
