# Generated by Django 3.2.2 on 2022-02-25 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20220224_1432'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0045_auto_20220225_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='prix_achat',
            new_name='prix',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='article',
            new_name='produit',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='quantité_en_vrac',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='user',
        ),
        migrations.AddField(
            model_name='produit',
            name='duree_conservation',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
        migrations.AddField(
            model_name='vente',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='quantite_vendu',
            field=models.PositiveIntegerField(null=True, verbose_name='quantite_vendu'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_entree',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.CharField(max_length=32)),
                ('moghataa', models.CharField(max_length=40)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
                ('vendeur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
