# Generated by Django 2.2.27 on 2022-02-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20220223_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode'),
        ),
    ]
