# Generated by Django 2.2.27 on 2022-02-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_qrcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='qrcode',
        ),
        migrations.AddField(
            model_name='client',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
