# Generated by Django 2.2.27 on 2022-02-24 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20220224_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='qr',
            new_name='img',
        ),
    ]
