# Generated by Django 3.2.2 on 2022-02-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20220224_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='client/qrcodes/'),
        ),
    ]
