# Generated by Django 3.2.2 on 2021-09-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.CharField(default='', max_length=5000),
            preserve_default=False,
        ),
    ]
