# Generated by Django 3.2.2 on 2021-09-25 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['id']},
        ),
    ]
