# Generated by Django 3.2.7 on 2021-09-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='manager',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
