# Generated by Django 3.2.7 on 2021-09-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='manager',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
